name: Build

on:
  push:
    tags: v*
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade hatch
    - name: Build package
      run: |
        hatch build --target kicad-package
    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: dist/*
        retention-days: 5
        if-no-files-found: error
