name: Main Workflow

on:
  push:
    tags: v*
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    name: Test package
    runs-on: ubuntu-latest
    container: admwscki/kicad-kbplacer-primary:nightly-lunar

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pytest
    - name: Run tests
      run: |
        python3 -m pytest

  build:
    name: Build package
    needs:
    - test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade hatch
    - name: Build package
      run: |
        hatch build --target kicad-package
    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: dist/*
        retention-days: 5
        if-no-files-found: error

  publish:
    name: Publish package
    needs:
    - build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: dist
    - name: Add binary assets to current release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
